name: Visual Regression

on:
  pull_request:

jobs:
  visual-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Python dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Django server
        run: |
          python manage.py runserver &
          sleep 10

      - name: Run screenshot tests
        run: |
          echo "Generate screenshots here"

      - name: PixellPeep Compare
        run: |
          pixellpeep compare \
            --base ./baseline \
            --current ./current \
            --post-github-check true
        env:
          PIXELLPEEP_API_KEY: ${{ secrets.PIXELLPEEP_API_KEY }}
