name: Visual Regression

on:
  pull_request:

jobs:
  visual-test:
    runs-on: ubuntu-latest

    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Node
        uses: actions/setup-node@v5
        with:
          node-version: 24

      - name: Install dependencies
        run: npm install

      - name: Run screenshots
        run: npm run screenshots

      - name: PixellPeep Compare
        run: |
          npx pixellpeep compare \
            --base ./baseline \
            --current ./current \
            --post-github-check true
        env:
          PIXELLPEEP_API_KEY: ${{ secrets.PIXELLPEEP_API_KEY }}
